window.$$iPems.lang = {
    Ok: '确定',
    Cancel: '取消',
    Close: '关闭',
    Operate: '操作',
    Add: '新增',
    Edit: '编辑',
    Delete: '删除',
    Clear: '清空',
    Refresh: '刷新',
    Query: '数据查询',
    Save: '保存',
    Import: '数据导出',
    Reset: '重置',
    All: '全部',
    Logout: '安全退出',
    SysTipTitle: '系统提示',
    SysWarningTitle: '系统警告',
    SysErrorTitle: '系统错误',
    ConfirmWndTitle: '确认对话框',
    ConfirmDelete: '您确认要删除吗？',
    FormError: '表单填写错误',
    AjaxHandling: '正在处理，请稍后...',
    YesTrue: '是',
    YesFalse: '否',
    StatusTrue: '有效',
    StatusFalse: '禁用',
    StatusLocked: '锁定',
    StatusUnlocked: '正常',
    DisplayRows: '显示条数',
    AllEmptyText: '默认全部',
    PlsSelectEmptyText: '请选择条件...',
    PlsInputEmptyText: '请输入筛选条件...',
    SearchEmptyText: '未找到指定内容:<br/>{0}',
    SearchEndText: '搜索完毕',
    MultiConditionEmptyText: '多条件请以;分隔，例: A;B;C',
    Component: {
        All:'全部',
        AreaName: '所属区域',
        AreaType: '区域类型',
        StationName: '所属站点',
        StationType: '站点类型',
        RoomType: '机房类型',
        DeviceType: '设备类型',
        AlarmLevel: '告警级别',
        LogicType: '逻辑分类',
        PointType: '信号类型',
        Employee: '隶属员工'
    },
    Site: {
        MenuNavTitle: '我的菜单',
        MenuNavRoot: '系统主页',
        AboutTitle: '关于...',
        DI: '遥信',
        AI: '遥测',
        AO: '遥调',
        DO: '遥控'
    },
    Role: {
        Title: '角色信息列表',
        MenuError: '请选择菜单权限',
        AreaError: '请选择区域权限',
        ToolBar: {
            Add: '新增角色',
            Name: '角色名称'
        },
        Window:{
            AddTitle: '新增角色',
            EditTitle: '编辑角色',
            ID: '角色标识',
            Name: '角色名称',
            Comment: '角色备注',
            Enabled: '角色状态',
            EnabledLabel: '(勾选表示启用)',
            MenuTitle: '菜单权限',
            AreaTitle: '区域权限',
            OperateTitle: '操作权限'
        },
        Columns:{
            Index: '序号',
            ID: '角色标识',
            Name: '角色名称',
            Comment: '角色备注',
            Enabled: '角色状态'
        }
    },
    User: {
        Title: '用户信息列表',
        ConfirmReset: '您确认要重置密码吗？',
        ConfirmError: '密码不一致',
        ToolBar: {
            Add: '新增用户',
            Role: '角色名称',
            User: '用户名称'
        },
        Window: {
            AddTitle: '新增用户',
            EditTitle: '编辑用户',
            ID: '用户标识',
            Name: '用户名称',
            Role: '隶属角色',
            EmpName: '隶属员工',
            Password: '登录密码',
            Confirm: '确认密码',
            Limited: '有效日期',
            IsLockedOut: '锁定状态',
            Comment: '用户备注',
            Enabled: '用户状态',
            ResetPassword: '重置密码',
            LockedOutLabel: '(勾选锁定用户)',
            EnabledLabel: '(勾选表示启用)',
        },
        Columns: {
            Index: '序号',
            ID: '用户标识',
            Name: '用户名称',
            Role: '隶属角色',
            EmpName: '隶属员工',
            EmpNo: '工号',
            Sex: '性别',
            Mobile: '联系电话',
            Email: 'Email',
            Password: '登录密码',
            Confirm: '确认密码',
            Created: '创建日期',
            Limited: '有效日期',
            LastLogined: '最后登录日期',
            LastPasswordChanged: '密码更改日期',
            IsLockedOut: '锁定状态',
            LastLockedout: '最后锁定日期',
            Comment: '用户备注',
            Enabled: '用户状态'
        }
    },
    UCenter:{
        BaseTitle: '基本信息',
        ChangeTitle: '修改密码',
        LogoutTitle: '登出系统',
        OriginPassword: '当前密码',
        Password: '登录密码',
        Confirm: '确认密码',
        ConfirmError: '密码不一致',
        SavePassword: '保存密码',
        ConfirmChangePassword: '您确认要修改密码吗？',
        Name: '用户名称',
        Role: '隶属角色',
        EmpName: '隶属员工',
        EmpNo: '工号',
        Sex: '性别',
        Mobile: '联系电话',
        Email: 'Email',
        Created: '创建日期',
        Limited: '有效日期',
        LastPasswordChanged: '密码更改日期',
        IsLockedOut: '锁定状态',
        LastLockedout: '最后锁定日期',
        Comment: '用户备注'
    },
    Event: {
        Title: '日志信息列表',
        Confirm:'您确定要删除三个月之前的日志信息吗？',
        ToolBar: {
            Level: '日志级别',
            Type: '日志类型',
            BeginTime: '开始日期',
            EndTime: '结束日期',
            Clear: '清理日志'
        },
        Columns: {
            Index: '序号',
            Level: '日志级别',
            Type: '日志类型',
            ShortMessage: '日志摘要',
            FullMessage: '详细信息',
            IP: '客户端地址',
            Page: '页面Url',
            Referrer: '相关Url',
            User: '用户名称',
            Created: '记录日期'
        }
    },
    Notice: {
        Title: '系统消息列表',
        ToolBar:{
            Add: '新增消息',
            Begin: '开始日期',
            End: '结束日期'
        },
        Window: {
            AddTitle: '新增消息',
            EditTitle: '编辑消息',
            Title: '消息标题',
            Content: '详细信息',
            Role: '广播对象',
            Enabled: '消息状态',
            EnabledLabel: '(勾选表示启用)'
        },
        Columns: {
            Index: '序号',
            Title: '消息标题',
            Content: '详细信息',
            Created: '消息日期',
            Enabled: '消息状态'
        }
    },
    ActiveAlarm: {
        MenuNavTitle: '告警设备列表',
        ConditionTitle: '告警筛选条件',
        RateTitle: '告警分类占比',
        DetailTitle: '告警详细信息',
        ToolBar: {
            ConfirmAlarm: '告警确认',
            PointName: '信号名称',
            OtherOption: '其他选项',
            ShowConfirm: '已确认告警',
            ShowUnConfirm: '未确认告警',
            ShowProject: '工程告警',
            ShowUnProject: '非工程告警'
        },
        Chart:{
            PieTotal: '告警总量',
            PieRate: '告警占比'
        },
        Columns: {
            Level: '告警级别',
            Start: '告警时间',
            Id: '序号',
            Area: '所属区域',
            Station: '所属站点',
            Room: '所属机房',
            DevType: '设备类型',
            Device: '设备名称',
            Logic: '逻辑分类',
            Point: '信号名称',
            Comment: '告警描述',
            Value: '触发值',
            Frequency: '触发频次'
        }
    },
    ActivePoint: {
        MenuNavTitle: '信号设备列表',
        DashboardChart: '信号实时图表',
        DashboardGrid: '信号实时测值',
        RssTips: '信号订阅',
        GroupHeaderTpl: '{columnName}: {name} ({rows.length}条)',
        Window: {
            Rss: '订阅',
            RssTitle: '信号订阅',
            RssTips: '请尽量精确订阅条件，避免因数据过多导致网页响应迟缓，影响其他操作。',
            PointName: '信号名称',
            ControlTitle: '信号遥控参数',
            ControlOption0: '常开控制(0)',
            ControlOption1: '常闭控制(1)',
            ControlOption2: '脉冲控制(2)',
            Control: '遥控',
            AdjustTitle: '信号遥调参数',
            AdjustOption: '模拟量输出值',
            Adjust: '遥调',
        },
        Columns: {
            Area: '所属区域',
            Station: '所属站点',
            Room: '所属机房',
            DevType: '设备类型',
            DevName: '设备名称',
            Logic: '逻辑分类',
            Id: '信号ID',
            Name: '信号名称',
            TypeDisplay: '信号类型',
            ValueDisplay: '信号测值',
            StatusDisplay: '信号状态',
            Control: '遥控',
            Adjust: '遥调'
        }
    },
    Project:{
        Title: '工程管理',
        ToolBar: {
            ProjectName: '工程名称',
            StartTime: '开始时间',
            EndTime: '结束时间'
        },
        Window: {
            AddTitle: '添加工程',
            EditTitle: '编辑工程',
            Id: '工程标识',
            Name: '工程名称',
            StartTime: '开始时间',
            EndTime: '结束时间',
            Responsible: '负责人员',
            ContactPhone: '联系电话',
            Company: '施工公司',
            Comment: '备注',
            Enabled: '状态',
            EnabledLabel: '(勾选表示启用)'
        },
        Columns: {
            Index: '序号',
            Id: '工程标识',
            Name: '工程名称',
            StartTime: '开始时间',
            EndTime: '结束时间',
            Responsible: '负责人员',
            ContactPhone: '联系电话',
            Company: '施工公司',
            Creator: '创建人员',
            CreatedTime: '创建时间',
            Comment: '备注',
            Enabled: '状态'
        }
    },
    Appointment: {
        Title: '工程预约信息表',
        ConfirmContinue: '开始时间早于当前时间，您确定要继续吗？',
        ConfirmContinue2: '开始时间距现在不足30分钟，您确定要继续吗？',
        NodesError: '请勾选需要预约的监控点',
        ToolBar: {
            StartTime: '开始时间',
            EndTime: '结束时间',
            AddTitle: '新增预约',
            Type: '筛选类型',
            ProjectType: '按工程名称',
            AreaType: '按区域名称',
            StationType: '按站点名称',
            RoomType: '按机房名称',
            DeviceType: '按设备名称'
        },
        Window: {
            AddTitle: '新增预约',
            EditTitle: '编辑预约',
            DetailTitle: '预约详情',
            Name: '工程名称',
            StartTime: '开始时间',
            EndTime: '结束时间',
            Comment: '预约备注',
            Enabled: '启用标识',
            EnabledLabel: '(勾选表示启用)',
            DetailTitile: '预约详情',
            DetailArea: '预约区域',
            DetailStation: '预约站点',
            DetailRoom: '预约机房',
            DetailDevice: '预约设备',
        },
        Columns: {
            Index: '序号',
            Id: '预约编号',
            StartTime: '开始时间',
            EndTime: '结束时间',
            Name: '工程名称',
            Creator: '创建人',
            CreatedTime: '创建时间',
            Comment: '预约备注',
            Enabled: '启用标识',
        }
    },
    Report400101: {
        ConditionTitle: '区域统计条件',
        ChartTitle: '区域分类占比',
        GridTitle: '区域统计列表',
        GroupTpl: '{columnName}: {name} ({rows.length}条)',
        Chart: {
            PieTotal: '区域总量',
            PieRate: '类型占比',
        },
        Columns: {
            Index: '序号',
            Id: '编号',
            Name: '名称',
            Type: '类型',
            Comment: '备注',
            Enabled: '状态'
        }
    }
};